### ISSUE TITLE
Option to drop first layer when only one image is converted

### ISSUE THREAD

**Issue by K-Meech** [glencoesoftware/bioformats2raw#108]
Converting e.g. a 3d tiff stack (xyz) produces a directory ```0``` that contains the converted image.

The ```--no-ome-meta-export``` and ```--no-root-group``` can be used to remove all the metadata at this top level, but not to remove this level entirely.

Could an option be provided to drop this top layer? i.e. so the top layer directly includes the directories of the downsampling layers, rather than being nested under the ```0``` directory.

Thanks!

**Comment by chris-allan** [comment]
Similar to #109, you can achieve this with the use of `--scale-format-string`. This option has full Java format string semantics so if you only want to use one one of the arguments you can achieve it with something like `bioformats2raw --scale-format-string 'scale%2$d/' 'foo&sizeX=2028&sizeY=2048.fake' foo` which would give you a hierarchy like this:

```
foo
├── OME
│   └── METADATA.ome.xml
├── scale0
│   └── 0
│       └── 0
│           └── 0
│               ├── 0
│               │   ├── 0
│               │   └── 1
│               └── 1
│                   ├── 0
│                   └── 1
├── scale1
│   └── 0
│       └── 0
│           └── 0
│               └── 0
│                   └── 0
├── scale2
│   └── 0
│       └── 0
│           └── 0
│               └── 0
│                   └── 0
└── scale3
    └── 0
        └── 0
            └── 0
                └── 0
                    └── 0
```

**Comment by K-Meech** [comment]
Thanks for all the info! That's very useful
