### ISSUE TITLE
Default naming of downsampling layers

### ISSUE THREAD

**Issue by K-Meech** [glencoesoftware/bioformats2raw#109]
The downscaled layers produced by bioformats2raw are named 0, 1, 2, 3 etc...
This means they are quite easy to confuse with the chunk hierarchy, which is named in the same manner.

Would it be possible to change the naming to e.g. s0, s1, s2, s3 etc, to make this distinction clearer?
cc @constantinpape

**Comment by chris-allan** [comment]
No, we have no intention of changing the defaults at this time. There is tooling that depends on the current naming structure. However, if you prefer a different hierarchy you can achieve pretty much whatever you want with the existing `--scale-format-string` option. For example `bioformats2raw --scale-format-string 'series%d/scale%d' 'foo&sizeX=2028&sizeY=2048.fake' foo` would produce the following hierarchy:

```
foo
├── OME
│   └── METADATA.ome.xml
└── series0
    ├── scale0
    │   └── 0
    │       └── 0
    │           └── 0
    │               ├── 0
    │               │   ├── 0
    │               │   └── 1
    │               └── 1
    │                   ├── 0
    │                   └── 1
    ├── scale1
    │   └── 0
    │       └── 0
    │           └── 0
    │               └── 0
    │                   └── 0
    ├── scale2
    │   └── 0
    │       └── 0
    │           └── 0
    │               └── 0
    │                   └── 0
    └── scale3
        └── 0
            └── 0
                └── 0
                    └── 0
                        └── 0
```
