### ISSUE TITLE
Conversion directly from imageplus

### ISSUE THREAD

**Issue by K-Meech** [glencoesoftware/bioformats2raw#110]
Is there any way to give bioformats2raw an imageplus, rather than the filepath to an image?
For some use cases (e.g. converting image sequences of many individual tiff files or pngs), it would be very useful to be able to open in imageJ, and then convert to zarr from there.

Thanks for your help!

**Comment by chris-allan** [comment]
No, not really.

The goal of the project is to, in as performant a way as possible, take Bio-Formats reader input and produce Zarr output. There are lots more use cases to address if one is taking in memory arrays as input instead and we really don't have an intention at the moment to address them. If you want to propose changes along the lines of what you'd like to see please do. However, keep in mind that `bioformats2raw` is really only a few hundred lines of code. It may be substantially less work to implement something that is tailored to the `imageplus --> Zarr` workflow specifically.
