### ISSUE TITLE
bump to ngff v0.3 (add support for axes)

### ISSUE THREAD

**Issue by joshmoore** [glencoesoftware/bioformats2raw#113]
see:
 * https://github.com/ome/ngff/issues/35
 * https://github.com/ome/ome-zarr-py/pull/89

bioformats2raw 0.3+ can be upgraded to use the NGFF v0.3 spec. This adds an `axes` field which permits storing arrays less than 5D if the dimension size <= 1, though bioformats2raw and raw2ometiff can choose to continue store 5D arrays regardless.

cc: @constantinpape

**Comment by sbesson** [comment]
Discussed briefly today, given the dimension order is stored as 5D in METADATA.ome.xml, I would also assume that having this tool preserving a 5D representation and storing the dimension names under the `axes` field would be the minimal set of change and also ensure maximum compatibility with downstream utilities like `raw2ometiff`. Does `raw2ometiff` makes a hard check on the version of the `multiscales`? If not, it is possible raw2ometiff 0.3.0 would consume this change out of the box.

This raises the question of whether this issue also encompasses adding full support for the 0.3 specification. Concretely, that would mean a Zarr group with a 0.3.0 `bioformats2raw.layout` containing individual series using the multiscales 0.3 specification and arrays of less than 5 dimensions. In this case, as suggested by @melissalinkert, it might be better to look at `raw2ometiff` first.

**Comment by sbesson** [comment]
Is this issue effectively solved by https://github.com/glencoesoftware/bioformats2raw/issues/113 (jumping directly to the upcoming OME-NGFF 0.4 specification)?

**Comment by joshmoore** [comment]
I'd think so.

**Comment by melissalinkert** [comment]
Closing as discussed with @sbesson.
