### ISSUE TITLE
Add `MetadataOnly` to `METADATA.ome.xml`?

### ISSUE THREAD

**Issue by melissalinkert** [glencoesoftware/bioformats2raw#137]
Discussed briefly in formats meeting (/cc @joshmoore, @sbesson, @dgault). 

`METADATA.ome.xml` doesn't technically validate, because it doesn't have `MetadataOnly`, `BinData`, or `TiffData` under `Pixels`. This was sort of intentional, as adding a `MetadataOnly` here means that raw2ometiff then needs to remove it.  Since we're now using the output of bioformats2raw independent of raw2ometiff and suggesting that other applications could use `METADATA.ome.xml`, it probably makes sense to update this.

**Comment by joshmoore** [comment]
btw, apparently when there are plane elements this gets even trickier: https://github.com/ome/ome-zarr-metadata/commit/08e12f784e085adbf4ca6d384720443108f96cb6#diff-0bb17e0ecb4ac83835ee3800a1af71a12f644b0ce782c623ba97f8917916250eR54

**Comment by sbesson** [comment]
Is the `Plane` validation issue related to https://github.com/ome/bioformats/issues/3810 ? In this case, I think the issue came from `ome_types` rather than a core invalidity

**Comment by joshmoore** [comment]
Almost certainly.
