### ISSUE TITLE
bioformats2raw in conda-forge or bioconda

### ISSUE THREAD

**Issue by jkh1** [glencoesoftware/bioformats2raw#159]
Would it be possible to move the bioformats2raw conda package to either bioconda or conda-forge? Or should we duplicate the package in one of these channels?
The reason is that we increasingly use workflow management systems (WMS) for image processing and analysis and these WMS, in particular Galaxy and Nextflow deal with dependencies preferably/by default via these two conda channels.

**Comment by melissalinkert** [comment]
https://github.com/ome/conda-bioformats2raw is the better place to ask questions about the Conda package. The OME team maintains that package separately from bioformats2raw itself.

Closing here since I can't transfer the issue to https://github.com/ome/conda-bioformats2raw.
