### ISSUE TITLE
Can't remove series from directory structure with `--scale-format-string`

### ISSUE THREAD

**Issue by LucaMarconato** [glencoesoftware/bioformats2raw#179]
As suggested in the readme, I am trying to remove the series from the directory structure with the argument `--scale-format-string`.

The full command I am using is 
```
bioformats2raw data/Xenium_FFPE_Human_Breast_Cancer_Rep1_morphology_mip.ome.tif data.zarr/images/morphology_mip -p --max-workers 16 --no-root-group --no-ome-meta-export --scale-format-string '%2$d/'
```

Unfortunately I see that `.zattrs` doesn't fill in the path for the multiscale transformations, leading to the inability for `napari-ome-zarr` to open the image.

```
   "datasets" : [ {
      "path" : "",
      "coordinateTransformations" : [ {
        "scale" : [ 1.0, 1.0, 1.0, 0.2125, 0.2125 ],
        "type" : "scale"
      } ]
    }, {
      "path" : "",
      "coordinateTransformations" : [ {
        "scale" : [ 1.0, 1.0, 1.0, 0.425, 0.425 ],
        "type" : "scale"
      } ]
    }, 
...
```

**Comment by melissalinkert** [comment]
Thanks, @LucaMarconato. #181 should fix this issue; if you have a chance to test it, we'd welcome any feedback.

**Comment by giovp** [comment]
@melissalinkert thanks for taking a look at this! I wanted to try out #181 but couldn't install it in dev mode. I could only install it via conda. Could you walk me through the developer installation to check out #181 ?

Thanks!

**Comment by melissalinkert** [comment]
@giovp : from https://github.com/glencoesoftware/bioformats2raw/pull/181/checks:

- click `Gradle` on the left-hand side
- scroll to the bottom of the page and click `bioformats2raw` under `Artifacts`. That should download a `bioformats2raw.zip` file which is a build of bioformats2raw with the changes in #181 
- unzip `bioformats2raw.zip`
- unzip the extracted `bioformats2raw-0.7.0-SNAPSHOT.zip`
- run `bin/bioformats2raw` (with the usual options) from the unzipped `bioformats2raw-0.7.0-SNAPSHOT` directory

`bin/bioformat2raw --version` should show `Version = 0.7.0-SNAPSHOT`, indicating that this is a development build. If any of that doesn't work, just let us know.

**Comment by giovp** [comment]
fantastic, very useful, it works!

```
 "name" : "Image0",
    "datasets" : [ {
      "path" : "0",
      "coordinateTransformations" : [ {
        "scale" : [ 1.0, 1.0, 1.0, 0.2125, 0.2125 ],
        "type" : "scale"
      } ]
    }, {
      "path" : "1",
      "coordinateTransformations" : [ {
        "scale" : [ 1.0, 1.0, 1.0, 0.425, 0.425 ],
        "type" : "scale"
      } ]
    }, {
      "path" : "2",
      "coordinateTransformations" : [ {
        "scale" : [ 1.0, 1.0, 1.0, 0.85, 0.85 ],
        "type" : "scale"
      } ]
    }, {
    ```
