### ISSUE TITLE
Pyramidal OMETIFF does not show histogram in OMERO iviewer

### ISSUE THREAD

**Issue by snehashis-roy** [glencoesoftware/bioformats2raw#188]
Hello.
I converted a single resolution OMETIFF file that I obtained from Nikon Elements to pyramid OMETIFF, because OMERO can efficiently visualize pyramid OMETIFF files much faster. However, although OMERO (server 5.6.5 + iviewer 5.15.0 and server 5.6.6+iviewer 5.16.0) can show the image histogram in the iviewer for the single resolution OMETIFF, it does not show it on the pyramid OMETIFF.

Example images:
```
Non-pyramid image
https://hpc.nih.gov/~roys5/1.ome.tiff
Pyramid image
https://hpc.nih.gov/~roys5/2.ome.tiff
```
The pyramid image was converted from the non pyramid image via the following commands,
```
bioformats2raw -c null -h 1024 -w 1024 --max_workers 16 --no-nested -r 8 --target-min-size 1024 -p 1.ome.tiff $TMPDIR
raw2ometiff --compression uncompressed --max-workers=16 -p $TMPDIR  2.ome.tiff
```
The "Histogram" button is not highlighted on server 5.6.6 for 2.ome.tiff
<img width="490" alt="2023-01-19_21-05-35" src="https://user-images.githubusercontent.com/27572901/213602622-36989633-dfd8-476b-9899-4dcd40ce35c4.png">
and same for server 5.6.5
<img width="356" alt="2023-01-19_21-06-33" src="https://user-images.githubusercontent.com/27572901/213602750-0e6f99da-20f3-40f9-8201-5b9e96950375.png">

while the histogram button is highlighted and clickable for 1.ome.tiff.

**Comment by melissalinkert** [comment]
I believe this behavior is expected, and has everything to do with the specifics of how OMERO handles large images.

`1.ome.tiff` as you note has a single resolution - it is also much larger than OMERO's default threshold for a large image, which is [3192x3192](https://omero.readthedocs.io/en/stable/sysadmins/config.html#omero-pixeldata-max-plane-height). If your server has more or less default settings for large image handling, importing a large image with no pyramid will cause OMERO to internally calculate a pyramid before the image is available for viewing (a "clock" thumbnail will appear while this happens). See https://omero.readthedocs.io/en/stable/sysadmins/limitations.html#large-images. When OMERO internally generates the pyramid, it is able to calculate the information necessary to enable the `Show Histogram` checkbox.

Importing a large image that already includes a pyramid - whether that's the output of raw2ometiff or any other pyramid format - means that the histogram will not be calculated at all. See https://forum.image.sc/t/olympus-whole-slide-scanner-histogram-feature-not-available-in-omero-iviewer/56308.

This is ultimately an OMERO limitation, and not something we can address in bioformats2raw. I can't transfer this issue to any of the OMERO repositories, so closing here. You may wish to raise this on forum.image.sc or in https://github.com/ome/omero-server for other perspectives on the underlying problem.
