### ISSUE TITLE
use`--dimension-order`to overwrite one of Z/C/T axis to `position`?

### ISSUE THREAD

**Issue by BioinfoTongLI** [glencoesoftware/bioformats2raw#195]
Hello there,
Many thanks for the great tools! really enjoy using it and it's been a irreplacable tool in our pipeline now.

I am recently having some issue of one microscope producing wrong metadata: tile position saved as `T`. And the conversion works totally fine. Just with wrong diemnsion information.
after reading the help message. It doesn't seem me that there's a possibility to overwirte `T` to position, i.e. XYZCP using `--dimension-order`. I am fully aware that this is kind of an edge case, but just wondering if you have any walk-around for this?
Best,

**Comment by melissalinkert** [comment]
@BioinfoTongLI : no, bioformats2raw doesn't have a way to override dimension metadata that comes from Bio-Formats. The `--dimension-order` option specifies the order in which data should be written, but won't affect how the data is read from the original file(s) (and can't be used to change the number of positions).

If you can share an example dataset that shows this behavior, we can take a look on the Bio-Formats side and see if there are any obvious solutions.

**Comment by BioinfoTongLI** [comment]
Hi @melissalinkert, that would be great! I can share a google drive link with you. Should I email that link to you instead of posting it here?
There will be a `master` ome.tif and the `metadat.txt` inside. Both from micro-manager 2.0.
They both should be valid.
I was converting this stack using `bioformats2raw [path-to-master-tif] output.zarr`

**Comment by melissalinkert** [comment]
> Should I email that link to you instead of posting it here?

If you don't want to post a public link, best would be to send a private message to https://forum.image.sc/g/ome - that will reach the OME team, which includes everyone who works on Bio-Formats (and me).

**Comment by BioinfoTongLI** [comment]
@melissalinkert message sent! lmk if you need the rest of tiffs. The one in the folder is just the master. Many thanks!

**Comment by melissalinkert** [comment]
@BioinfoTongLI : yes, please do upload the complete dataset when you can (I know it's large). It will be difficult for us to test without all of the files.

**Comment by BioinfoTongLI** [comment]
@melissalinkert all uploaded now!

**Comment by melissalinkert** [comment]
Thanks for sending the dataset, @BioinfoTongLI. Closing this issue in favor of https://github.com/ome/bioformats/issues/3972.
