### ISSUE TITLE
Image over 2 giga pixel

### ISSUE THREAD

**Issue by olatarkowska** [glencoesoftware/bioformats2raw#20]
I have been processing images that are over 2GP and seems that data is not converted properly, For images that are 4GP looks like pyramid is corrupted. Could you please help me with identifying whats the problem?
<img width="597" alt="Screenshot 2020-03-26 at 11 29 10" src="https://user-images.githubusercontent.com/1065155/77647938-37fb1700-6f5f-11ea-8bba-3c99aec64b98.png">

That is persistant problem

**Comment by melissalinkert** [comment]
We saw something similar, and fixed in https://github.com/ome/bioformats/pull/3519 which was included in Bio-Formats 6.4.0.  Have you tried with the current master branch, which includes the bump to Bio-Formats 6.4.0 (from https://github.com/glencoesoftware/bioformats2raw/pull/16)?

**Comment by olatarkowska** [comment]
Thanks @melissalinkert for the quick reply, I am trying now!

**Comment by olatarkowska** [comment]
Thanks @melissalinkert problem solved
