### ISSUE TITLE
open n5 pyramid

### ISSUE THREAD

**Issue by olatarkowska** [glencoesoftware/bioformats2raw#21]
I have been trying to open pyramid.n5 in https://github.com/saalfeldlab/n5-viewer but I am getting error channels not found, can you guys point  which dir should viewer select exactly?

**Comment by melissalinkert** [comment]
n5-viewer requires a specific data layout which is different from what bioformats2raw writes.  See the ```Container structure``` section of https://github.com/saalfeldlab/n5-viewer/blob/master/README.md.

The n5 structures that bioformats2raw produces are not really intended to be used directly, just consumed by raw2ometiff.  Is working with the n5 output directly part of your workflow, or was this just related to investigating #20?
