### ISSUE TITLE
Topic addition: "ome-zarr-converters"

### ISSUE THREAD

**Issue by joshmoore** [glencoesoftware/bioformats2raw#225]
At the recent [Next generation bioimage analysis workflows hackathon](https://www.ema.uzh.ch/en/register/biovisioncenter-hackathon.html) in Zürich, a few other OME-Zarr converters were worked on. After a question about how we can make them more findable, the "ome-zarr-converter topic (https://github.com/topics/ome-zarr-converter) was added to a handful. I'd like to propose that we add the topic here as well as on https://github.com/glencoesoftware/isyntax2raw. We may eventually want to go further and provide a more dedicated list (here in the README, on ngff.o.org, etc.) but for the moment, it provides a low-overhead method of increasing discoverability.

**Comment by melissalinkert** [comment]
Added to https://github.com/topics/ome-zarr-converter; I don't have permission to do that for https://github.com/glencoesoftware/isyntax2raw, which I think is fine for now given the state of support for that repo.

**Comment by joshmoore** [comment]
Thanks, @melissalinkert.
