### ISSUE TITLE
Add -no-sas option as exists in bfconvert

### ISSUE THREAD

**Issue by dsudar** [glencoesoftware/bioformats2raw#250]
Would it be possible/easy to have the -no-sas option (as it exists in bfconvert) in bioformats2raw?

We're always fighting ways where PHI info sneaks into data that needs to become public. We want to switch to the bioformats2raw/raw2ometiff tools in favor of bfconvert but our SVS files have some problematic items in the metadata that ends up in the resulting ome.tif in SA's. So we want to keep the "regular" OME-XML metadata but not the SA stuff.

And I tried the --no-ome-meta-export option but then raw2ometiff is unhappy.

**Comment by melissalinkert** [comment]
Thanks @dsudar - #251 has a proposed fix.
