### ISSUE TITLE
Use NestedDirectoryStore for zarr format

### ISSUE THREAD

**Issue by joshmoore** [glencoesoftware/bioformats2raw#26]
As a follow-up to https://github.com/glencoesoftware/bioformats2raw/pull/24, a _nested_ zarr layout should be used in order to prevent too many files in a single directory. This may require a PR against n5-zarr.

**Comment by chris-allan** [comment]
Nested chunk storage was added in #80 (0.3.0rc1), made the default with #94 (0.3.0rc2), and some command line option issues fixed in #99 (0.3.0rc4). The final 0.3.0 release will ship with full nested layout support as the default storage format. Closing.
