### ISSUE TITLE
Is bioformats2raw Windows compatible? 

### ISSUE THREAD

**Issue by ofrag** [glencoesoftware/bioformats2raw#34]
Is bioformats2raw Windows compatible? 
what are the libblosc installation instructions for Windows ?

**Comment by camlloyd** [comment]
I have some environments in the form of `environment.yml` files which may be useful. Perhaps something like this can be added to get people up and running faster? 

Hopefully then as simple as `conda env create`.

cc @melissalinkert @chris-allan

**Comment by chris-allan** [comment]
Yes, bioformats2raw is compatible with Windows. You can either disable Blosc compression via `--compression=raw` (any Blosc warnings can then be safely ignored) or compile the blosc.dll as outlined in the c-blosc README:

 * https://github.com/Blosc/c-blosc

**Comment by chris-allan** [comment]
@camlloyd: Thanks for the insight. At this time that's not something I think we would add to the main repository as something we support. Honestly, I'd rather put time into a fork of `c-blosc` with AppVeyor builds producing Windows artifacts that people can just download and use.

**Comment by camlloyd** [comment]
@chris-allan no problem  - that sounds like a good idea! 

My only reason for doing this on Windows is that I use the same on macOS, instead of homebrew.

Thanks for the quick response!
