### ISSUE TITLE
help to install bioformats2raw tool

### ISSUE THREAD

**Issue by Mohammedhusen** [glencoesoftware/bioformats2raw#39]
Hi Team,

Could you please help to bioformats2raw tool as I stuck in gradle command.

**Comment by chris-allan** [comment]
Pre-built release downloads are here:

 * https://github.com/glencoesoftware/bioformats2raw/releases

Usage is detailed here:

 * https://github.com/glencoesoftware/bioformats2raw/blob/master/README.md

If you have problems with installing the Blosc dependency for your platform, please disable compression as outlined here:

 * https://github.com/glencoesoftware/bioformats2raw/issues/34
