### ISSUE TITLE
Black background color for brightfield images

### ISSUE THREAD

**Issue by camlloyd** [glencoesoftware/bioformats2raw#45]
https://github.com/glencoesoftware/bioformats2raw/blob/1f0ea0e52357bbd82a48a2c4b25c3b2d1fcaa289/src/main/java/com/glencoesoftware/bioformats2raw/MiraxReader.java#L195-L197

This makes sense for fluorescence images, but can this be set to white/`255` for brightfield images to match CaseViewer?

**Comment by camlloyd** [comment]
@melissalinkert is it possible for generated `--rgb` OME-TIFFs to respect this (for visualisation and thresholding reasons?)

Thanks

**Comment by chris-allan** [comment]
Fill color adjustment for MRXS was added in #65 and has been shipping since 0.3.0rc1. Closing.

**Comment by camlloyd** [comment]
Thank you @chris-allan!
