### ISSUE TITLE
Couldn't find build/distributions

### ISSUE THREAD

**Issue by mohammed-sawi** [glencoesoftware/bioformats2raw#47]
Hello, I started learning python so I may use your program to batch convert files so I am very new, but I'm mot sure where I should put your new releases. Whenever I  run the command gradle clean build and change directory I always get an error saying it couldn't find the "distributions" folder. 

Do I make the folders myself and put in the latest release (In my case -0.2.4 & 0.2.6)? I couldn't find any instructions.

I you would like to see my code it is attached
![code snip](https://user-images.githubusercontent.com/67711582/86289302-771db180-bbb9-11ea-8e88-774baeb2b89e.PNG)

**Comment by joshmoore** [comment]
If you are using conda for your Python environment (and don't _need_ to re-build the application), you could use: `conda install -c ome bioformats2raw` which would install the executable on your PATH. Alternatively, you can download from https://github.com/glencoesoftware/bioformats2raw/releases/download/v0.2.4/bioformats2raw-0.2.4.zip

**Comment by chris-allan** [comment]
As @joshmoore has mentioned and has already been mentioned on #39, built artifacts are available for all releases:

 * https://github.com/glencoesoftware/bioformats2raw/releases
