### ISSUE TITLE
Order of converted channels and Number of output pixels not matching original slide

### ISSUE THREAD

**Issue by ofrag** [glencoesoftware/bioformats2raw#55]
Hi,

We followed your blog and converted mrxs files (acquired with 3D Histech slide scanner) and encountered 2 problems: 
1) The order of converted channels does not match the original channel order
2) The output number of pixels is bigger than the original one 

The input file (as viewed with CaseViewer) has 3 channels:
1. DAPI_Q
2. FITC_Q
3. TRITC_Q

The converted tiff file has 3 channels with the same order of names, however the actual content of the channels is different. 

Ch1 - named DAPI_Q - is actually TRITC_Q 
Ch2 - named FITC_Q - is the correct FITC_Q
Ch3 - named TRITC_Q - is actually DAPI_Q

The Input number of pixels is: 32512 * 46080 with micrometer / pixel = 0.325
The output number of pixels is: 45219 * 110213 with pixel width = 0.325 um

It seems to me from inspecting the image in QuPath that many empty pixels are appended to the real data in the converted file. This is not desired from disk space point of view, but also since it prevent me from opening the file in Fiji as the number of pixels becomes too big for Fiji. 

The actual intensity values seems to be fine.

We used bioformats2raw with "--resolutions 6 " or without the resolutions  parameter and got the same output. 

Thanks
Ofra

**Comment by melissalinkert** [comment]
Thanks for reporting this, @ofrag.  Would you be able to make an example dataset available so that we can investigate?

**Comment by chris-allan** [comment]
Closing. @ofrag, please reopen if you are able to provide some example data.

**Comment by melissalinkert** [comment]
Sample data provided privately, investigation forthcoming.

**Comment by melissalinkert** [comment]
This should have been fixed by #58 and #59, which were included in 0.3.0rc1 and later.
