### ISSUE TITLE
Support to Roche Ventana DP200 files [FR]

### ISSUE THREAD

**Issue by Tato14** [glencoesoftware/bioformats2raw#66]
The last release of bioformats [support this kind of files](https://github.com/ome/bioformats/pull/3573). I would like to know if this update would be also implemented in `bioformats2raw`

**Comment by melissalinkert** [comment]
Thanks for mentioning this, @Tato14.  Once #67 is merged and included in a release, ```bioformats2raw``` will support Ventana files with a ```LEFT``` overlap.

**Comment by chris-allan** [comment]
Resolved by #67
