### ISSUE TITLE
Add -series flag (a la bfconvert) to select from a multi-image input file

### ISSUE THREAD

**Issue by dsudar** [glencoesoftware/bioformats2raw#70]
Many WSI images contain a slide label image and a macro image that are currently converted along with the main image. Sometimes those little images contain PHI data or other proprietary data that should be stripped out during conversion. Possible to add that new feature similar to bfconvert's -series flag?

**Comment by melissalinkert** [comment]
#71 adds ```-s```/```--series```, which should work exactly like ```bfconvert -series```.

**Comment by dsudar** [comment]
Works great. Thanks Melissa!

**Comment by chris-allan** [comment]
Closing as the feature from is now shipping as of 0.3.0rc1.
