### ISSUE TITLE
RFE: deploy jar to artifactory/nexus

### ISSUE THREAD

**Issue by joshmoore** [glencoesoftware/bioformats2raw#73]
In order to consume `Converter` from other projects, it'd be useful to have the jar deployed to a maven repository.

**Comment by melissalinkert** [comment]
Completely forgot that we have https://repo.glencoesoftware.com/#browse/browse:bioformats2raw2ometiff (see https://github.com/glencoesoftware/raw2ometiff/blob/master/build.gradle#L24).  Is that sufficient, or does the jar need to be deployed somewhere else?

**Comment by chris-allan** [comment]
Closing. As @melissalinkert has mentioned above, we are deploying bioformats2raw artifacts automatically via the build system to the https://repo.glencoesoftware.com/repository/bioformats2raw2ometiff/ repository.
