### ISSUE TITLE
Command-line option for changing the log level

### ISSUE THREAD

**Issue by andreasg123** [glencoesoftware/bioformats2raw#74]
Currently, one can only choose among the log levels `debug` or `info`. As `info` is still very verbose, it would be great to be able to select `warn` or other log levels.

**Comment by melissalinkert** [comment]
Thanks, @andreasg123.  One way of doing this is proposed in #75.

**Comment by andreasg123** [comment]
Thanks for addressing this so quickly. It would be great if you could add the same to [raw2ometiff](https://github.com/glencoesoftware/raw2ometiff).

**Comment by joshmoore** [comment]
Included in https://github.com/glencoesoftware/raw2ometiff/pull/48
